# Generated by Django 2.1.7 on 2019-02-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='user',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='humans',
        ),
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='class code', max_length=90),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='teacher name', max_length=90),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(default='class subject', max_length=90),
        ),
        migrations.DeleteModel(
            name='Human',
        ),
    ]
