# Generated by Django 2.1.5 on 2019-02-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keywords',
            field=models.CharField(default='Expectation', max_length=9000),
        ),
    ]
