# Generated by Django 2.1.5 on 2019-02-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20190217_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
