# Generated by Django 2.1.7 on 2019-02-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20190216_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacherEmail',
            field=models.CharField(default='teacher email', max_length=90),
        ),
    ]
