# Generated by Django 2.1.7 on 2019-02-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_classroom_teacheremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='description', max_length=90),
        ),
    ]
