# Generated by Django 2.1.7 on 2019-02-17 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0004_classroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='Code', max_length=90),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='Enter Description Here...', max_length=90),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='Enter Name Here...', max_length=90),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(default='Enter Subject Here...', max_length=90),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacherEmail',
            field=models.CharField(default='Email', max_length=90),
        ),
    ]
