# Generated by Django 2.1.7 on 2019-02-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20190217_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='teacherEmail',
            new_name='owner',
        ),
    ]
